[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"
author = "vollkorntomate"

[dependencies]


[[bin]]
name = "01_1"
path = "src/01_1/main.rs"

[[bin]]
name = "01_2"
path = "src/01_2/main.rs"